config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :parcels
  resources :users
  get '/about' => 'welcome#about'
  get '/products' => 'products#index'
  get '/products/:id/refresh' => 'products#refresh'
  get '/products/refreshAll' => 'products#refreshAll'
  get '/brands/:id' => 'brands#show'
  get '/items/bestsellers' => 'items#bestSellers'
  get '/items/discount' => 'items#discount'
  get '/welcome/playwithbootstrap' => 'welcome#playwithbootstrap'

end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
	belongs_to :buyer, class_name: "User"
	belongs_to :seller, class_name: "User"
end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController
	before_action :authenticate_user!
	def index
	end

	def new
		@buyers = User.where("role = ?", 0)
		@parcel = Parcel.new
	end

	def create
		@seller = current_user
		@buyer = User.find(params[:parcel][:buyer_id])
		date = Date.new(params[:parcel]['shiped_date(1i)'].to_i,params[:parcel]['shiped_date(2i)'].to_i,params[:parcel]['shiped_date(3i)'].to_i)
	    @parcel = Parcel.new
	    @parcel.buyer = @buyer
	    @parcel.seller = @seller
	    @parcel.track_no = params[:parcel][:track_no]
	    @parcel.shiped_date = date
	    @parcel.delivered = params[:parcel][:delivered]
	    @parcel.description = params[:parcel]['description']
	    respond_to do |format|
			if @parcel.save
				format.html { redirect_to parcels_path, notice: 'Parcel was successfully created.' }
				# format.json { render :show, status: :created, location: @parcel }
			else
				format.html { render :new }
				# format.json { render json: @parcel.errors, status: :unprocessable_entity }
			end
	    end
  	end

  	def edit
  		@buyers = User.where("role = ?", 0)
  		@parcel = Parcel.find(params[:id])
  	end

  	def update
  		@parcel = Parcel.find(params[:id])
  		@buyer = User.find(params[:parcel][:buyer_id])
  		date = Date.new(params[:parcel]['shiped_date(1i)'].to_i,params[:parcel]['shiped_date(2i)'].to_i,params[:parcel]['shiped_date(3i)'].to_i)
	    @parcel.buyer = @buyer
	    @parcel.track_no = params[:parcel][:track_no]
	    @parcel.shiped_date = date
	    @parcel.delivered = params[:parcel][:delivered]
	    @parcel.description = params[:parcel]['description']
  		respond_to do |format|
			if @parcel.save
				format.html { redirect_to parcels_path, notice: 'Parcel was successfully updated.' }
				# format.json { render :show, status: :created, location: @parcel }
			else
				format.html { render :new }
				# format.json { render json: @parcel.errors, status: :unprocessable_entity }
			end
	    end
  	end
end

app/helpers/parcels_helper.rb
module ParcelsHelper
end

app/views/parcels/_form.html.erb
<%= form_for(@parcel) do |f| %>
  <% if @parcel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parcel.errors.count, "error") %> prohibited this parcel from being saved:</h2>
      <ul>
      <% @parcel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :快递单号 %><br />
    <%= f.text_field :track_no %>
  </div>
  <div class="field">
    <%= f.label :收件人电邮 %><br />
    <%= f.date_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "创建" %>
  </div>
<% end %>

app/views/parcels/edit.erb
<h1>编辑快递信息</h1>

<%= form_for(@parcel) do |f| %>
  <% if @parcel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parcel.errors.count, "error") %> prohibited this parcel from being saved:</h2>
      <ul>
      <% @parcel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :快递单号 %><br />
    <%= f.text_field :track_no %>
  </div>
  <div class="field">
    <%= f.label :收件人 %><br />
    <%= f.collection_select(:buyer_id, @buyers, :id, :name_with_email)  %>
  </div>
  <div class="field">
    <%= f.label :物品信息 %><br />
    <%= f.text_area :description, size: "30x12" %>
  </div>
  <div class="field">
    <%= f.label :投递日期 %><br />
    <%= f.date_select :shiped_date %>
  </div>
  <div class="field">
    <%= f.radio_button(:delivered, :true) %>
    <%= f.label :已送达 %><br />
    <%= f.radio_button(:delivered, :false) %>
    <%= f.label :在途 %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "更改" %>
  </div>
<% end %>

app/views/parcels/index.erb
<% if current_user.buyer? %>
	<% if current_user.inParcels.count == 0%>
		你没有快递单
	<% else %>
		<table class="table table-striped">
			<thead>
				<td>单号</td>
				<td>收件人</td>
				<td>寄件人</td>
				<td>状态</td>
				<td>投递日期</td>
				<td>描述</td>
				<td></td>
			</thead>
		    <tbody>
		    	<% current_user.inParcels.order(:delivered, shiped_date: :desc).each do |parcel| %>
					<tr>
					  <td>
					  	<%= parcel.track_no %>
					  </td>					  
					  <td>
					  	<%= parcel.buyer.name_with_email %>
					  </td>
					  <td>
					  	<%= parcel.seller.name_with_email %>
					  </td>
					  <td>
					  	<%= parcel.delivered ? "已送达" : "在途" %>
					  </td>
					  <td>
					  	<%= parcel.shiped_date %>
					  </td>
					  <td>
					  	<%= parcel.description %>
					  </td>
					  <td>
					  	<a type="button" class="btn btn-default" href=<%="http://www.hyexpress.com.au/cgi-bin/GInfo.dll?EmmisTrack&w=auhyexpress&cno=#{parcel.track_no}&cmodel=&ntype=0"%>>追踪</a>
					  </td>
					</tr>
			    <% end %>
		    </tbody>
		</table>
	<% end %>
<% elsif current_user.seller? %>
	<% if current_user.outParcels.count == 0%>
		你没有在途快递单
	<% else %>
		<table class="table table-striped">
			<thead>
				<td>单号</td>
				<td>收件人</td>
				<td>寄件人</td>
				<td>状态</td>
				<td>投递日期</td>
				<td>描述</td>
				<td></td>
			</thead>
		    <tbody>
		    	<% current_user.outParcels.order(:buyer_id, :delivered, shiped_date: :desc).each do |parcel| %>
					<tr>

					  <td>
					  	<%= parcel.track_no %>
					  </td>					  
					  <td>
					  	<%= parcel.buyer.name_with_email %>
					  </td>
					  <td>
					  	<%= parcel.seller.name_with_email %>
					  </td>
					  <td>
					  	<%= parcel.delivered ? "已送达" : "在途" %>
					  </td>
					  <td>
					  	<%= parcel.shiped_date %>
					  </td>
					  <td>
					  	<%= parcel.description %>
					  </td>
					  <td>
					  	<a type="button" class="btn btn-default" href=<%="http://www.vip-express.com.au/yy/myInfo/search.action?doccode=#{parcel.track_no}"%>>追踪</a>
					  	<a><%= link_to '编辑', edit_parcel_path(parcel), :class =>  'btn btn-default' %></a>
					  </td>
					</tr>
			    <% end %>
		    </tbody>
		</table>
	<% end %>
<% elsif current_user.admin? %>
开发中
<% else %>
滚粗，你没资格查看这个页面。
<% end %>

app/views/parcels/new.erb
<h1>创建快递信息</h1>

<%= form_for(@parcel) do |f| %>
  <% if @parcel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parcel.errors.count, "error") %> prohibited this parcel from being saved:</h2>
      <ul>
      <% @parcel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :快递单号 %><br />
    <%= f.text_field :track_no %>
  </div>
  <div class="field">
    <%= f.label :收件人 %><br />
    <%= f.collection_select(:buyer_id, @buyers, :id, :name_with_email)  %>
  </div>
  <div class="field">
    <%= f.label :物品信息 %><br />
    <%= f.text_area :description, size: "30x12" %>
  </div>
  <div class="field">
    <%= f.label :投递日期 %><br />
    <%= f.date_select :shiped_date %>
  </div>
  <div class="field">
    <%= f.radio_button(:delivered, :true) %>
    <%= f.label :已送达 %><br />
    <%= f.radio_button(:delivered, :false) %>
    <%= f.label :在途 %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "创建" %>
  </div>
<% end %>