config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :parcels
  resources :users
  get '/about' => 'welcome#about'
  get '/products' => 'products#index'
  get '/products/:id/refresh' => 'products#refresh'
  get '/products/refreshAll' => 'products#refreshAll'
  get '/brands/:id' => 'brands#show'
  get '/items/bestsellers' => 'items#bestSellers'
  get '/items/discount' => 'items#discount'
  get '/welcome/playwithbootstrap' => 'welcome#playwithbootstrap'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :inParcels, foreign_key: "buyer_id", class_name: "Parcel"
	has_many :outParcels, foreign_key: "seller_id", class_name: "Parcel"
	enum role: [:buyer, :seller, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def name_with_email
  		self.name + ", " +self.email
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, :check_authorization
	def index
		@users = User.all
		# @buyers = User.where("role = ?", 0)
	end

  	def edit
  		@user = User.find(params[:id])
  	end

  	def update
  		@user = User.find(params[:id])
  		if params[:user][:role].nil?
  			nil
  		else
  			if params[:user][:role] == "admin"
  				raise User::NotAuthorized
  			else
  				@user.role = params[:user][:role]
  			end
  		end
  		@user.distribution = params[:user][:distribution]
  		@user.name = params[:user][:name]
  		respond_to do |format|
			if @user.save
				format.html { redirect_to users_path, notice: 'User info was successfully updated.' }
				# format.json { render :show, status: :created, location: @parcel }
			else
				format.html { render :new }
				# format.json { render json: @parcel.errors, status: :unprocessable_entity }
			end
	    end
  	end

  	private
	    # If the user is not authorized, just throw the exception.
	    def check_authorization
	      raise User::NotAuthorized unless current_user.admin?
	    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.erb
<h1>用户管理</h1>
<% if current_user && current_user.admin? %>
	<%= form_for(@user) do |f| %>
	  <% if @user.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
	      <ul>
	      <% @user.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  <br>
	  <div class="field">
	    <%= f.label :电子邮件 %><br />
	    <%= f.text_field :email, :readonly => true %>
	  </div>
	  <div class="field">
	    <%= f.label :姓名 %><br />
	    <%= f.text_field :name %>
	  </div>
	  <div class="field">
	    <%= f.label :权限管理 %><br />
	    <%= f.radio_button(:role, :buyer) %>
	    <%= f.label :买家 %><br />
	    <%= f.radio_button(:role, :seller) %>
	    <%= f.label :卖家 %><br />
	    <%= f.radio_button(:role, :admin, :disabled => true) %>
	    <%= f.label :管理员 %>
	  </div>
	  <div class="field">
	    <%= f.label :分销商 %><br />
	    <%= f.radio_button(:distribution, :true) %>
	    <%= f.label :是 %><br />
	    <%= f.radio_button(:distribution, :false) %>
	    <%= f.label :否 %>
	  </div>
	  <div class="actions">
	    <%= f.submit "更改" %>
	  </div>
	<% end %>
<% else %>
滚粗，你没资格来这里
<% end %>

app/views/users/index.erb
<% if current_user && current_user.admin? %>
	<table class="table table-striped">
		<thead>
			<td>电子邮件</td>
			<td>姓名</td>
			<td>权限</td>
			<td>分销商</td>
			<td></td>
		</thead>
	    <tbody>
	    	<% @users.each do |user| %>
		      <tr>
		          <td>
		          	<%= user.email %>
		          </td>
		          <td>
		          	<%= user.name %>
		          </td>
		          <td>
		          	<%= user.role %>
		          </td>
		          <td>
		          	<%= user.distribution ? "是" : "否" %>
		          </td>
		          <td>
		         	<a><%= link_to '编辑', edit_user_path(user), :class =>  'btn btn-default' %></a>
		          </td>
		      </tr>
		    <% end %>
	    </tbody>
	</table>
<% else %>
你没资格来这里，滚粗。
<% end %>