config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :parcels
  resources :users
  get '/about' => 'welcome#about'
  get '/products' => 'products#index'
  get '/products/:id/refresh' => 'products#refresh'
  get '/products/refreshAll' => 'products#refreshAll'
  get '/brands/:id' => 'brands#show'
  get '/items/bestsellers' => 'items#bestSellers'
  get '/items/discount' => 'items#discount'
  get '/welcome/playwithbootstrap' => 'welcome#playwithbootstrap'

end

app/views/layouts/_footer.erb
<footer>
	<div class="container">
		<p>
			&copy; Wen Liang 2015
		</p>
		<p>
			加个页脚和Copy Right标识显得有逼格
		</p>
		<p>
			国际惯例，再加上学校名字，University of Melbourne
		</p>
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>老板买点什么</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">
    <ul class="nav navbar-nav">
      <li>
        <a href="/"><span class="glyphicon glyphicon-home"></span>首页</a>
      </li>
      <li>
        <a href="/items/bestsellers"><span class="glyphicon glyphicon-book"></span>常见物品</a>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-list"></span>物品分类<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% @brands = Brand.all %>
            <% @brands.each do |brand| %>
              <li><%= link_to "#{brand.name}", controller: "/brands", action: "show", id: brand.id%></li>
            <% end %>
            <% if current_user && current_user.distribution %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "特价汇总", items_discount_path %></li>
            <% end %>
          </ul>
      </li>
      <% if user_signed_in? %>
        <% if current_user.buyer? %>
          <li>
            <a href="/parcels"><span class="glyphicon glyphicon-plane"></span>我的快递单
              <% count=current_user.inParcels.where("delivered=?", false).count; if count > 0 %>
                <span class="badge"><%= count %></span>
              <% end %>
            </a>
          </li>
        <% elsif current_user.seller? %>
          <li>
            <a href="/parcels"><span class="glyphicon glyphicon-plane"></span>我的快递单
              <% count=current_user.outParcels.where("delivered=?", false).count; if count > 0 %>
                <span class="badge"><%= count %></span>
              <% end %>
            </a>
          </li>
          <li>
            <a href="/parcels/new"><span class="glyphicon glyphicon-import"></span>添加快递单</a>
          </li>
        <% elsif current_user.admin? %>
          <li>
            <a href="/users"><span class="glyphicon glyphicon-import"></span>用户列表</a>
          </li>
          <li>
            <a href="/parcels"><span class="glyphicon glyphicon-plane"></span>快递单列表</a>
          </li>
        <% end %>
      <% end %>
      <li>
        <a href="/about"><span class="glyphicon glyphicon-user"></span>关于本站</a>
      </li>
    </ul>

    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        欢迎， <strong><%= current_user.email %></strong>
        <%= link_to '编辑账号', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "登出", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "注册", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "登入", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
  </div>
</nav>


<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>